name: Build package

on:
  push:
    branches:
      - "technical/create_workflow"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: ros-tooling/setup-ros@v0.3
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: parking_patrol
          target-ros2-distro: foxy
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos

#test