name: Colcon test build

on:
  pull_request:
    branches:
      - "master"
    paths:
      -"parking_patrol/**"
      -"parking_patrol_msgs/**"

jobs:
  test-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
