name: Colcon test build
on:
  pull_request:
    paths-ignore:
      - "parking_patrol/**"
      - "parking_patrol_msgs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
